# Generated by Django 3.2.4 on 2021-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='', max_length=2),
        ),
    ]
